### ISSUE TITLE
Trouble getting the lovelace-card to work.

### ISSUE THREAD

**Issue by Monkeyfacemoney** [Miicroo/lovelace-vasttrafik-card#1]
Dear Magnus,  

I'm quite new to HA and adding cards manually.

What I've done so far:

 * Added vasttrafik-card.js, vasttrafik-card-editor.js, vasttrafik-card.css  from the dist folder to:
../www/community/lovelace-vasttrafik-card

* Added your version of vasttrafik sensor (ha-vasttrafik) to:
../custom_components/vasttrafik

* I also added the url of the lovelace .js files via the GUI:
https://my.home-assistant.io/redirect/lovelace_resources/

With these entries:
- url: /local/community/lovelace-vasttrafik-card/vasttrafik-card.js
type: module
- url: /local/community/lovelace-vasttrafik-card/vasttrafik-card-editor.js 
type: module

* Restarted HA and the browser but when I try to add the card with yaml in the editor of HA it gets this error:

![image](https://user-images.githubusercontent.com/25419293/180874777-ff9c200e-86d8-4214-96cd-df9f83f4e95b.png)

Sincerely yours, 
MonkeyFaceMoney

**Comment by Miicroo** [comment]
@Monkeyfacemoney Hey! Glad that someone else is testing this card out too! :D
I can't find any obvious problems, your installation method and config should work fine. Can you check to see if the code you added is the raw source code or if it is wrapped in HTML? I know that can happen on manual installation from github (done it myself a few times 😊 ). If so, you can download all files as zip and overwrite the old ones: https://github.com/Miicroo/lovelace-vasttrafik-card/archive/refs/heads/master.zip

**Comment by Miicroo** [comment]
@Monkeyfacemoney 
Found one oddity in the configuration now that I took a second look!
I think that it might be the extra `type: ''` added after `sensor.godhemsgdatan_till_brunnsparken`

**Comment by Miicroo** [comment]
Closing as stale issue, please reopen if problem is still there
