### ISSUE TITLE
make it installable via HACS

### ISSUE THREAD

**Issue by funkyfisch** [Miicroo/lovelace-vasttrafik-card#6]
I will gladly help with a pull request on this one, it should be easy to add using HACS

**Comment by Miicroo** [comment]
Sure, all PRs are welcome! Not 100% sure what you mean with installable via HACS, it is already possible to install this through HACS? Haven't added any instructions in the readme or a hacs.json though, so those things might make it easier

**Comment by Miicroo** [comment]
Been open for almost a year, closing as already fixed
